// <auto-generated />
using System;
using DV8.Console.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DV8.Console.Migrations
{
    [DbContext(typeof(DV8DbContext))]
    partial class DV8DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DV8.Console.Data.CcpDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CcpDecisions");
                });

            modelBuilder.Entity("DV8.Console.Data.DbgSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DbgHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Geo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RiskFloor")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DbgSessions");
                });

            modelBuilder.Entity("DV8.Console.Data.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Kind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasFilter("[Fingerprint] IS NOT NULL");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DV8.Console.Data.DiscoveryJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidrs")
                        .HasColumnType("TEXT");

                    b.Property<string>("DbgSession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PassiveOnly")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiscoveryJobs");
                });

            modelBuilder.Entity("DV8.Console.Data.DiscoveryResult", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Addrs")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("Raw")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signals")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId", "Fingerprint");

                    b.ToTable("DiscoveryResults");
                });

            modelBuilder.Entity("DV8.Console.Data.HoacEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Profile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Risk")
                        .HasColumnType("int");

                    b.Property<byte[]>("Transcript")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("HoacEvents");
                });

            modelBuilder.Entity("DV8.Console.Data.Interface", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ipv4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ipv6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpeedMbps")
                        .HasColumnType("int");

                    b.Property<bool?>("Up")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Interfaces");
                });

            modelBuilder.Entity("DV8.Console.Data.Neighbor", b =>
                {
                    b.Property<Guid>("AIfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZIfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Proto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.HasKey("AIfId", "ZIfId", "Proto");

                    b.HasIndex("ZIfId");

                    b.ToTable("Neighbors");
                });

            modelBuilder.Entity("DV8.Console.Data.SecretField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Aad")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Ciphertext")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Iv")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LedgerPtr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("SecretFields");
                });

            modelBuilder.Entity("DV8.Console.Data.DiscoveryResult", b =>
                {
                    b.HasOne("DV8.Console.Data.DiscoveryJob", "Job")
                        .WithMany("Results")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DV8.Console.Data.HoacEvent", b =>
                {
                    b.HasOne("DV8.Console.Data.Device", "Device")
                        .WithMany("HoacEvents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DV8.Console.Data.Interface", b =>
                {
                    b.HasOne("DV8.Console.Data.Device", "Device")
                        .WithMany("Interfaces")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DV8.Console.Data.Neighbor", b =>
                {
                    b.HasOne("DV8.Console.Data.Interface", "AInterface")
                        .WithMany("NeighborsA")
                        .HasForeignKey("AIfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DV8.Console.Data.Interface", "ZInterface")
                        .WithMany("NeighborsZ")
                        .HasForeignKey("ZIfId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AInterface");

                    b.Navigation("ZInterface");
                });

            modelBuilder.Entity("DV8.Console.Data.SecretField", b =>
                {
                    b.HasOne("DV8.Console.Data.Device", "Device")
                        .WithMany("SecretFields")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DV8.Console.Data.Device", b =>
                {
                    b.Navigation("HoacEvents");

                    b.Navigation("Interfaces");

                    b.Navigation("SecretFields");
                });

            modelBuilder.Entity("DV8.Console.Data.DiscoveryJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("DV8.Console.Data.Interface", b =>
                {
                    b.Navigation("NeighborsA");

                    b.Navigation("NeighborsZ");
                });
#pragma warning restore 612, 618
        }
    }
}
